In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.dates as mdates
plt.style.use('ggplot')

df = pd.read_csv('~/Downloads/ga.csv')

In [2]:
df['pagePathNormal'] = df['pagePath'].apply(lambda x: x.split('?')[0])

In [3]:
t = df.groupby(['pagePathNormal', 'cd1'])

In [4]:
res = t.first()

## Number of pages in Adobe analytics

In [5]:
# Number of pages in 2.0
len(df['cd1'].unique())

17344

## Number of pages in en-ie

In [6]:
# Number of english pages
df = df.dropna()
df = df.dropna(subset=['cd4'])
en = df[df['cd4'].str.contains('en-ie')]
en = en.drop_duplicates(subset=['cd1'])
it = df[df['cd4'].str.contains('it-it')]
it = it.drop_duplicates(subset=['cd1'])

en.shape

(1594, 7)

## Pages by category

In [7]:
# Page categories
def grouppages(x):
    return x.split(':')[0]
en['category'] = en['cd1'].apply(grouppages)
it['category'] = it['cd1'].apply(grouppages)

en['category'].value_counts().reset_index()

             index  category
0          flights       898
1    travel expert       252
2      useful-info       226
3        plan-trip       104
4       management        24
5          booking        17
6          checkin        15
7             none        10
8   screenscrapers         9
9        corporate         7
10       myryanair         7
11           rooms         6
12      refundfaqs         4
13    gift-voucher         3
14          header         3
15  inside-ryanair         2
16        register         1
17   special-offer         1
18  getting-around         1
19           login         1
20       samsonite         1
21  travel-updates         1
22   group-booking         1

## Tagging scope

In [8]:
def scope(x):
    if x == 'flights':
        return 'SEO pages'
    elif x == 'travel expert':
        return 'TSN'
    else:
        return '2.0'
en['category_group'] = en['category'].apply(scope)
it['category_group'] = it['category'].apply(scope)

en['category_group'].value_counts().reset_index()

       index  category_group
0  SEO pages             898
1        2.0             444
2        TSN             252

## Type of 2.0 pages

In [9]:
def cd1scope(x):
    return x.split(':')[0]
#en['cd1'].apply(cd1scope).value_counts()
en[en['category_group'].str.contains('2.0')]['cd1'].apply(cd1scope).value_counts().reset_index()

             index  cd1
0      useful-info  226
1        plan-trip  104
2       management   24
3          booking   17
4          checkin   15
5             none   10
6   screenscrapers    9
7        corporate    7
8        myryanair    7
9            rooms    6
10      refundfaqs    4
11    gift-voucher    3
12          header    3
13  inside-ryanair    2
14   special-offer    1
15  travel-updates    1
16           login    1
17  getting-around    1
18        register    1
19   group-booking    1
20       samsonite    1

## Review by category

In [10]:
en[en['category'].str.contains('none')]

,UniqueSessions,cd1,cd2,cd3,cd4,pagePath,pagePathNormal,category,category_group
724,1,none: resetpassword,website: en-ie: none: resetpassword,ver.spa-beta,en-ie,/ie/en/reset/66e27153-3779-4de3-861e-1ff84c1119aa,/ie/en/reset/66e27153-3779-4de3-861e-1ff84c1119aa,none,2.0
1121,1,none: fare_finder: results,website: en-ie: none: fare_finder: results,ver.spa-beta,en-ie,/ie/en/cheap-flights/edinburgh-to-brussels-cha...,/ie/en/cheap-flights/edinburgh-to-brussels-cha...,none,2.0
1341,1,none: fare_finder: details,website: en-ie: none: fare_finder: details,ver.spa-beta,en-ie,/ie/en/cheap-flights/dublin-to-seville?out-fro...,/ie/en/cheap-flights/dublin-to-seville,none,2.0
1520,1,none: route_map,website: en-ie: none: route_map,ver.spa-beta,en-ie,/ie/en/cheap-flights/london-stansted-to-vienna...,/ie/en/cheap-flights/london-stansted-to-vienna,none,2.0
1893,1,none: redirect,website: en-ie: none: redirect,ver.spa-beta,en-ie,/ie/en/redirect?booking=WSG7YSGYMPS4JSKNAP56UF...,/ie/en/redirect,none,2.0
8872,1,none: fare_finder,website: en-ie: none: fare_finder,ver.spa-beta,en-ie,/ie/en/cheap-flights/?from=BTS&out-from-date=2...,/ie/en/cheap-flights/,none,2.0
210299,2,none: forgotpassword,website: en-ie: none: forgotpassword,ver.spa-beta,en-ie,/ie/en/mytrips/summary,/ie/en/mytrips/summary,none,2.0
331143,2,none: timetables,website: en-ie: none: timetables,ver.spa-beta,en-ie,/ie/en/check-in,/ie/en/check-in,none,2.0
341912,6405,none: homepage,website: en-ie: none: homepage,ver.spa-beta,en-ie,/ie/en/,/ie/en/,none,2.0
344171,420,none: route-list,website: en-ie: none: route-list,ver.spa-beta,en-ie,/ie/en/cheap-flight-destinations-list,/ie/en/cheap-flight-destinations-list,none,2.0

- 2.0 pages should we keep the value none?

In [11]:
en[en['category'].str.contains('plan-trip')]

,UniqueSessions,cd1,cd2,cd3,cd4,pagePath,pagePathNormal,category,category_group
6194,1,plan-trip: travel-documentation,website: en-ie: plan-trip: travel-documentation,ver.spa-beta,en-ie,/ie/en/plan-trip/travel-documentation?fbclid=I...,/ie/en/plan-trip/travel-documentation,plan-trip,2.0
9754,1,plan-trip: flying-with-us: my-ryanair,website: en-ie: plan-trip: flying-with-us: my-...,ver.spa-beta,en-ie,/ie/en/plan-trip/flying-with-us/my-ryanair?cmp...,/ie/en/plan-trip/flying-with-us/my-ryanair,plan-trip,2.0
13825,1,plan-trip: explore: flight-deals-and-sales,website: : plan-trip: explore: flight-deals-an...,ver.spa-beta,en-ie,/ie/en/plan-trip/explore/flight-deals-and-sale...,/ie/en/plan-trip/explore/flight-deals-and-sales,plan-trip,2.0
23197,1,plan-trip: explore: cyber-week-6,website: en-ie: plan-trip: explore: cyber-week-6,ver.spa-beta,en-ie,/ie/en/plan-trip/explore/cyber-week-6?onsid=ry...,/ie/en/plan-trip/explore/cyber-week-6,plan-trip,2.0
36262,1,plan-trip: explore: getaways,website: en-ie: plan-trip: explore: getaways,ver.spa-beta,en-ie,/ie/en/plan-trip/explore/getaways?cmpid=email_...,/ie/en/plan-trip/explore/getaways,plan-trip,2.0
...,...,...,...,...,...,...,...,...,...
4054855,1,plan-trip: travel-extras: ryanair-car-hire: cork,website: : plan-trip: travel-extras: ryanair-c...,ver.spa-beta,en-ie,/ie/en/plan-trip/travel-extras/ryanair-car-hir...,/ie/en/plan-trip/travel-extras/ryanair-car-hir...,plan-trip,2.0
4876779,1,plan-trip: explore: cyber-week-4,website: en-ie: plan-trip: explore: cyber-week-4,ver.spa-beta,en-ie,/ie/en/plan-trip/explore/cyber-week-4,/ie/en/plan-trip/explore/cyber-week-4,plan-trip,2.0
4980318,1,plan-trip: travel-extras: ryanair-car-hire: ha...,website: : plan-trip: travel-extras: ryanair-c...,ver.spa-beta,en-ie,/ie/en/plan-trip/travel-extras/ryanair-car-hir...,/ie/en/plan-trip/travel-extras/ryanair-car-hir...,plan-trip,2.0
4980762,1,plan-trip: travel-extras: ryanair-car-hire: co...,website: : plan-trip: travel-extras: ryanair-c...,ver.spa-beta,en-ie,/ie/en/plan-trip/travel-extras/ryanair-car-hir...,/ie/en/plan-trip/travel-extras/ryanair-car-hir...,plan-trip,2.0
5014572,1,plan-trip: explore: cheap-deals:,website: : plan-trip: explore: cheap-deals:,ver.spa-beta,en-ie,/ie/en/plan-trip/explore/cheap-deals/?cmpid=em...,/ie/en/plan-trip/explore/cheap-deals/,plan-trip,2.0

## Plan trip

Break down:

https://www.ryanair.com/fr/fr/planifier-un-voyage/destinations/vols-pour-gerone 

to

website: : planifier-un-voyage: destinations: vols-pour

https://www.ryanair.com/ie/en/plan-trip/explore/flight-deals-and-sales

to website: : plan-trip: explore: flight-deals-and-sales

Similar for all the other "translated hits"

In [12]:
en[en['category_group'].str.contains('SEO pages')]

,UniqueSessions,cd1,cd2,cd3,cd4,pagePath,pagePathNormal,category,category_group
11926,1,flights: flights-from-naples-to-milan,website: en-ie: flights: flights-from-naples-t...,ver.spa-beta,en-ie,/flights/ie/en/flights-from-naples-to-milan,/flights/ie/en/flights-from-naples-to-milan,flights,SEO pages
29863,1,flights: flights-from-milan-to-barcelona,website: en-ie: flights: flights-from-milan-to...,ver.spa-beta,en-ie,/flights/ie/en/flights-from-milan-to-barcelona,/flights/ie/en/flights-from-milan-to-barcelona,flights,SEO pages
44892,1,flights: flights-from-lisbon-to-budapest,website: en-ie: flights: flights-from-lisbon-t...,ver.spa-beta,en-ie,/flights/ie/en/flights-from-lisbon-to-budapest,/flights/ie/en/flights-from-lisbon-to-budapest,flights,SEO pages
46797,1,flights: flights-from-bucharest-to-milan,website: en-ie: flights: flights-from-buchares...,ver.spa-beta,en-ie,/flights/ie/en/flights-from-bucharest-to-milan,/flights/ie/en/flights-from-bucharest-to-milan,flights,SEO pages
48650,1,flights: flights-from-dublin-to-mykonos,website: en-ie: flights: flights-from-dublin-t...,ver.spa-beta,en-ie,/flights/ie/en/flights-from-dublin-to-mykonos,/flights/ie/en/flights-from-dublin-to-mykonos,flights,SEO pages
...,...,...,...,...,...,...,...,...,...
4991067,1,flights: flights-from-cork-to-zadar,website: en-ie: flights: flights-from-cork-to-...,ver.spa-beta,en-ie,/flights/ie/en/flights-from-cork-to-zadar,/flights/ie/en/flights-from-cork-to-zadar,flights,SEO pages
5002001,1,flights: flights-from-hamburg-to-zadar,website: en-ie: flights: flights-from-hamburg-...,ver.spa-beta,en-ie,/flights/ie/en/flights-from-hamburg-to-zadar,/flights/ie/en/flights-from-hamburg-to-zadar,flights,SEO pages
5013378,1,flights: flights-to-nuremberg,website: en-ie: flights: flights-to-nuremberg,ver.spa-beta,en-ie,/flights/ie/en/flights-to-nuremberg,/flights/ie/en/flights-to-nuremberg,flights,SEO pages
5030878,1,flights: flights-from-krakow-to-brindisi,website: en-ie: flights: flights-from-krakow-t...,ver.spa-beta,en-ie,/flights/ie/en/flights-from-krakow-to-brindisi,/flights/ie/en/flights-from-krakow-to-brindisi,flights,SEO pages
5031118,1,flights: flights-from-nis-to-berlin,website: en-ie: flights: flights-from-nis-to-b...,ver.spa-beta,en-ie,/flights/ie/en/flights-from-nis-to-berlin,/flights/ie/en/flights-from-nis-to-berlin,flights,SEO pages

In [13]:
## Control for SEO pages
it[it['category_group'].str.contains('SEO pages')]

,UniqueSessions,cd1,cd2,cd3,cd4,pagePath,pagePathNormal,category,category_group
1537,1,flights: voli-da-lisbona-a-cagliari,website: it-it: flights: voli-da-lisbona-a-cag...,ver.spa-beta,it-it,/flights/it/it/voli-da-lisbona-a-cagliari,/flights/it/it/voli-da-lisbona-a-cagliari,flights,SEO pages
2037,1,flights: voli-da-genova-a-napoli,website: it-it: flights: voli-da-genova-a-napoli,ver.spa-beta,it-it,/flights/it/it/voli-da-genova-a-napoli?fbclid=...,/flights/it/it/voli-da-genova-a-napoli,flights,SEO pages
24158,1,flights: voli-da-varsavia-a-pisa,website: it-it: flights: voli-da-varsavia-a-pisa,ver.spa-beta,it-it,/flights/it/it/voli-da-varsavia-a-pisa,/flights/it/it/voli-da-varsavia-a-pisa,flights,SEO pages
30973,1,flights: voli-da-copenaghen-a-charleroi,website: it-it: flights: voli-da-copenaghen-a-...,ver.spa-beta,it-it,/flights/it/it/voli-da-copenaghen-a-charleroi,/flights/it/it/voli-da-copenaghen-a-charleroi,flights,SEO pages
41618,1,flights: voli-da-stoccarda-a-alghero,website: it-it: flights: voli-da-stoccarda-a-a...,ver.spa-beta,it-it,/flights/it/it/voli-da-stoccarda-a-alghero,/flights/it/it/voli-da-stoccarda-a-alghero,flights,SEO pages
...,...,...,...,...,...,...,...,...,...
5033492,1,flights: voli-da-bergamo-a-santander,website: it-it: flights: voli-da-bergamo-a-san...,ver.spa-beta,it-it,/flights/it/it/voli-da-bergamo-a-santander,/flights/it/it/voli-da-bergamo-a-santander,flights,SEO pages
5034377,1,flights: voli-a-cote-d'azur,website: it-it: flights: voli-a-cote-d'azur,ver.spa-beta,it-it,/flights/it/it/voli-a-cote-d'azur,/flights/it/it/voli-a-cote-d'azur,flights,SEO pages
5041884,1,flights: voli-da-trapani-a-praga,website: it-it: flights: voli-da-trapani-a-praga,ver.spa-beta,it-it,/flights/it/it/voli-da-trapani-a-praga,/flights/it/it/voli-da-trapani-a-praga,flights,SEO pages
5043596,1,flights: voli-da-lamezia-terme-a-saragozza,website: it-it: flights: voli-da-lamezia-terme...,ver.spa-beta,it-it,/flights/it/it/voli-da-lamezia-terme-a-saragozza,/flights/it/it/voli-da-lamezia-terme-a-saragozza,flights,SEO pages
5080500,1,flights: voli-da-barcellona-a-brindisi,website: it-it: flights: voli-da-barcellona-a-...,ver.spa-beta,it-it,/flights/it/it/voli-da-barcellona-a-brindisi,/flights/it/it/voli-da-barcellona-a-brindisi,flights,SEO pages

## Pages left in 2.0

In [14]:
en[en['category_group'].str.contains('2.0')]['cd1'].apply(cd1scope).value_counts().reset_index().drop([0,1]).sum()

index    managementbookingcheckinnonescreenscraperscorp...
cd1                                                    114
dtype: object

In [18]:
en[en['category_group'].str.contains('2.0')].reset_index()

,index,UniqueSessions,cd1,cd2,cd3,cd4,pagePath,pagePathNormal,category,category_group
0,3,1,checkin: select,website: en-ie: checkin: select,ver.spa-beta,en-ie,/ie/en/booking/active/checkin?tripId=93963238-...,/ie/en/booking/active/checkin,checkin,2.0
1,4,1,checkin: priority-boarding,website: en-ie: checkin: priority-boarding,ver.spa-beta,en-ie,/ie/en/booking/active/checkin?tripId=f6fab10c-...,/ie/en/booking/active/checkin,checkin,2.0
2,18,1,management: active_trip,website: en-ie: management: active_trip,ver.spa-beta,en-ie,/ie/en/booking/active/manage-trip/home?tripId=...,/ie/en/booking/active/manage-trip/home,management,2.0
3,19,1,management: flightchange: confirm and pay,website: en-ie: management: flightchange: conf...,ver.spa-beta,en-ie,/ie/en/booking/active/manage-trip/change-fligh...,/ie/en/booking/active/manage-trip/change-flight,management,2.0
4,36,1,checkin: allocation,website: en-ie: checkin: allocation,ver.spa-beta,en-ie,/ie/en/booking/active/checkin?tripId=TripBased...,/ie/en/booking/active/checkin,checkin,2.0
...,...,...,...,...,...,...,...,...,...,...
439,4876779,1,plan-trip: explore: cyber-week-4,website: en-ie: plan-trip: explore: cyber-week-4,ver.spa-beta,en-ie,/ie/en/plan-trip/explore/cyber-week-4,/ie/en/plan-trip/explore/cyber-week-4,plan-trip,2.0
440,4910969,1,useful-info: travelling-with-children:,website: : useful-info: travelling-with-childr...,ver.spa-beta,en-ie,/ie/en/useful-info/travelling-with-children/,/ie/en/useful-info/travelling-with-children/,useful-info,2.0
441,4980318,1,plan-trip: travel-extras: ryanair-car-hire: ha...,website: : plan-trip: travel-extras: ryanair-c...,ver.spa-beta,en-ie,/ie/en/plan-trip/travel-extras/ryanair-car-hir...,/ie/en/plan-trip/travel-extras/ryanair-car-hir...,plan-trip,2.0
442,4980762,1,plan-trip: travel-extras: ryanair-car-hire: co...,website: : plan-trip: travel-extras: ryanair-c...,ver.spa-beta,en-ie,/ie/en/plan-trip/travel-extras/ryanair-car-hir...,/ie/en/plan-trip/travel-extras/ryanair-car-hir...,plan-trip,2.0
443,5014572,1,plan-trip: explore: cheap-deals:,website: : plan-trip: explore: cheap-deals:,ver.spa-beta,en-ie,/ie/en/plan-trip/explore/cheap-deals/?cmpid=em...,/ie/en/plan-trip/explore/cheap-deals/,plan-trip,2.0

## Questions

- Should we keep the translated version of the pages?
    - How do you manage then to attribute conversion to a specific page?
    
- Can we apply the same logic for all the other 2.0 pages?
    - How do we structure then management/booking/checkin/none pages?
    
- If we are not going with a translated version how do we identify a page?